# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 048c59a679d6dec896deb67bec18da584c9f7ad4cacf98fe4240d0095fa9f4b702d1171c58562459aea3d6d58e7aefba9c6575eda3182fd147dce5f44658d2ac

test:
  secret_key_base: 38bf6ca07b22789c95cbb632d469d558fa96ee1ccd330c8ecd5d858921d02025f2d4f489a4f44dd755b16b26f85e91c92ab1f49ab17fc8a56ccd090326bc7953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
